/* Oportunidades publicadas.
   Espelha o model `Oportunidade` (proposta de modelo de dados, M6/M9).

   Duas coisas propositais aqui:

   1. `prazoInscricao` é data ISO (AAAA-MM-DD), nunca texto formatado. No
      protótipo o prazo era a string "30/09/2026", e ordenar por ela comparava o
      dia primeiro — 05/10 aparecia antes de 30/09, invertendo a urgência.

   2. `universidadesAlvo` só vale para estágio de empresa (lista vazia = todas).
      Oportunidade acadêmica não usa esse campo: a universidade dela vem da
      instituição que publicou, via `universidadeVinculada`. */

export const TIPO_OPORTUNIDADE = {
  ESTAGIO: "estagio",
  MONITORIA: "monitoria",
  IC: "ic",
  LIGA_ACADEMICA: "liga_academica",
  EQUIPE_COMPETICAO: "equipe_competicao",
};

export const ROTULO_TIPO = {
  [TIPO_OPORTUNIDADE.ESTAGIO]: "Estágio",
  [TIPO_OPORTUNIDADE.MONITORIA]: "Monitoria",
  [TIPO_OPORTUNIDADE.IC]: "Iniciação científica",
  [TIPO_OPORTUNIDADE.LIGA_ACADEMICA]: "Liga acadêmica",
  [TIPO_OPORTUNIDADE.EQUIPE_COMPETICAO]: "Equipe de competição",
};

export const MODALIDADE = {
  PRESENCIAL: "presencial",
  HIBRIDO: "hibrido",
  REMOTO: "remoto",
};

export const ROTULO_MODALIDADE = {
  [MODALIDADE.PRESENCIAL]: "Presencial",
  [MODALIDADE.HIBRIDO]: "Híbrido",
  [MODALIDADE.REMOTO]: "Remoto",
};

export const STATUS_OPORTUNIDADE = {
  RASCUNHO: "rascunho",
  ABERTA: "aberta",
  ENCERRADA: "encerrada",
};

export const FORMA_CANDIDATURA = {
  PLATAFORMA: "plataforma",
  EXTERNA: "externa",
};

const T = TIPO_OPORTUNIDADE;
const M = MODALIDADE;
const S = STATUS_OPORTUNIDADE;

export const oportunidades = [
  // ===================== PUC-Rio — monitoria =========================
  {
    id: 1,
    instituicaoId: 10,
    tipo: T.MONITORIA,
    titulo: "Monitoria de Cálculo a Várias Variáveis",
    descricao:
      "Apoio às listas de exercícios e plantão de dúvidas duas vezes por semana, para as turmas do diurno. A monitoria inclui participação na reunião semanal de acompanhamento com a professora responsável.",
    requisitos: [
      "Ter cursado Cálculo a Várias Variáveis com grau mínimo 7",
      "Disponibilidade para dois plantões semanais no campus",
      "Boa comunicação escrita para correção comentada de listas",
    ],
    beneficios: [
      "Bolsa mensal e certificado de monitoria",
      "Contato próximo com o corpo docente do departamento",
      "Experiência de ensino que conta para seleção de IC",
    ],
    cursosAlvo: [1, 2, 7, 9],
    periodoMinimo: 3,
    crMinimo: 7.0,
    cargaHorariaSemanal: 12,
    remunerada: true,
    valorBolsa: 600,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-09-30",
    responsavelNome: "Profa. Ana Ribeiro",
    responsavelContato: "ana.ribeiro@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-01",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },
  {
    id: 2,
    instituicaoId: 11,
    tipo: T.MONITORIA,
    titulo: "Monitoria de Programação I",
    descricao:
      "Acompanhamento do laboratório e correção comentada dos trabalhos em Python das turmas iniciantes. O monitor participa da elaboração dos exercícios de fixação.",
    requisitos: [
      "Ter cursado Programação I com bom aproveitamento",
      "Domínio de Python e de Git",
      "Disponibilidade nos horários de laboratório",
    ],
    beneficios: [
      "Bolsa mensal e certificado",
      "Primeira experiência formal de ensino",
      "Prioridade em projetos do laboratório de software",
    ],
    cursosAlvo: [2, 3],
    periodoMinimo: 2,
    crMinimo: 6.5,
    cargaHorariaSemanal: 8,
    remunerada: true,
    valorBolsa: 450,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-09-28",
    responsavelNome: "Prof. Marcos Teixeira",
    responsavelContato: "marcos.teixeira@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-02",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 3,
  },
  {
    id: 3,
    instituicaoId: 12,
    tipo: T.MONITORIA,
    titulo: "Monitoria de Física Experimental",
    descricao:
      "Preparação das bancadas e apoio aos grupos durante os experimentos do laboratório básico, incluindo conferência dos relatórios de medição.",
    requisitos: [
      "Ter cursado Física Experimental I",
      "Cuidado com equipamento de laboratório",
    ],
    beneficios: [
      "Certificado de monitoria voluntária",
      "Treinamento em instrumentação de laboratório",
    ],
    cursosAlvo: [2, 7, 8, 10],
    periodoMinimo: 2,
    crMinimo: null,
    cargaHorariaSemanal: 10,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-05",
    responsavelNome: "Profa. Clara Nogueira",
    responsavelContato: "clara.nogueira@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-03",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },

  // ===================== PUC-Rio — iniciação científica ==============
  {
    id: 4,
    instituicaoId: 11,
    tipo: T.IC,
    titulo: "Visão computacional para inspeção industrial",
    descricao:
      "Treinar e avaliar modelos de detecção de defeitos em imagens de linha de produção, em parceria com uma empresa do setor. O bolsista participa das reuniões quinzenais com o parceiro industrial.",
    requisitos: [
      "Python e biblioteca de machine learning (PyTorch ou TensorFlow)",
      "Álgebra linear e estatística básica",
      "Disponibilidade de 20h semanais",
    ],
    beneficios: [
      "Bolsa PIBIC por 12 meses",
      "Coautoria em artigo submetido a congresso",
      "Acesso ao cluster de GPU do departamento",
    ],
    cursosAlvo: [2, 3],
    periodoMinimo: 4,
    crMinimo: 7.5,
    cargaHorariaSemanal: 20,
    remunerada: true,
    valorBolsa: 1100,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-10",
    responsavelNome: "Prof. Rafael Amorim",
    responsavelContato: "rafael.amorim@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-04",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 1,
  },
  {
    id: 5,
    instituicaoId: 13,
    tipo: T.IC,
    titulo: "Materiais sustentáveis para construção",
    descricao:
      "Ensaios de resistência com agregados reciclados e organização da base de resultados do laboratório de materiais.",
    requisitos: [
      "Ter cursado Materiais de Construção",
      "Excel ou Python para tratamento de dados de ensaio",
    ],
    beneficios: [
      "Bolsa PIBIC por 12 meses",
      "Prática em laboratório de ensaios mecânicos",
    ],
    cursosAlvo: [7, 1],
    periodoMinimo: 5,
    crMinimo: 7.0,
    cargaHorariaSemanal: 16,
    remunerada: true,
    valorBolsa: 1100,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-02",
    responsavelNome: "Profa. Beatriz Sales",
    responsavelContato: "beatriz.sales@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-05",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },
  {
    id: 6,
    instituicaoId: 14,
    tipo: T.IC,
    titulo: "Economia comportamental e decisão de crédito",
    descricao:
      "Revisão de literatura e apoio na análise dos dados de um experimento sobre escolha de crédito estudantil.",
    requisitos: [
      "Econometria básica",
      "R ou Stata",
      "Inglês para leitura de artigos",
    ],
    beneficios: [
      "Certificado de iniciação científica voluntária",
      "Participação na redação do relatório final",
    ],
    cursosAlvo: [4],
    periodoMinimo: 3,
    crMinimo: 7.0,
    cargaHorariaSemanal: 12,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-15",
    responsavelNome: "Prof. Daniel Barroso",
    responsavelContato: "daniel.barroso@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-06",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 1,
  },

  // ===================== PUC-Rio — ligas acadêmicas ==================
  {
    id: 7,
    instituicaoId: 30,
    tipo: T.LIGA_ACADEMICA,
    titulo: "Processo seletivo 2026.2",
    descricao:
      "Vagas nas diretorias de projetos e de eventos, com participação nas reuniões semanais e nos projetos de consultoria com empresas parceiras.",
    requisitos: [
      "Disponibilidade para reunião semanal presencial",
      "Interesse em consultoria e gestão de projetos",
    ],
    beneficios: [
      "Certificado de atividade complementar",
      "Projetos reais com empresas parceiras",
      "Rede de contatos com ex-membros no mercado",
    ],
    cursosAlvo: [],
    periodoMinimo: 1,
    crMinimo: null,
    cargaHorariaSemanal: 6,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-09-26",
    responsavelNome: "Marina Duarte, diretora de gente",
    responsavelContato: "selecao@ligaempreende.org",
    status: S.ABERTA,
    publicadaEm: "2026-09-01",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.EXTERNA,
    linkExterno: "https://forms.gle/exemplo-liga-empreendedorismo",
    vagas: 8,
  },
  {
    id: 8,
    instituicaoId: 31,
    tipo: T.LIGA_ACADEMICA,
    titulo: "Diretoria de marketing e conteúdo",
    descricao:
      "Produção dos relatórios semanais de mercado e das publicações da liga, junto com a equipe de análise.",
    requisitos: [
      "Boa escrita em português",
      "Noções de mercado financeiro",
    ],
    beneficios: [
      "Certificado de atividade complementar",
      "Portfólio de publicações assinadas",
    ],
    cursosAlvo: [4, 5, 1],
    periodoMinimo: 2,
    crMinimo: null,
    cargaHorariaSemanal: 8,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.REMOTO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-03",
    responsavelNome: "Pedro Lins, presidente",
    responsavelContato: "contato@ligafinancas.org",
    status: S.ABERTA,
    publicadaEm: "2026-09-02",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 4,
  },
  {
    id: 9,
    instituicaoId: 32,
    tipo: T.LIGA_ACADEMICA,
    titulo: "Grupo de estudos em direito digital",
    descricao:
      "Encontros quinzenais de discussão de casos e escrita de pareceres curtos, abertos a alunos de qualquer curso.",
    requisitos: ["Interesse em regulação de tecnologia e proteção de dados"],
    beneficios: [
      "Certificado de atividade complementar",
      "Pareceres publicados no blog da liga",
    ],
    cursosAlvo: [],
    periodoMinimo: 1,
    crMinimo: null,
    cargaHorariaSemanal: 4,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-08",
    responsavelNome: "Júlia Ferraz, coordenadora",
    responsavelContato: "ligadireitotech@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-03",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 10,
  },

  // ===================== PUC-Rio — equipes de competição =============
  {
    id: 10,
    instituicaoId: 40,
    tipo: T.EQUIPE_COMPETICAO,
    titulo: "Subsistema de suspensão e direção",
    descricao:
      "Projeto e montagem do protótipo para a competição nacional, com oficina aos sábados e uso de CAD para o dimensionamento das peças.",
    requisitos: [
      "Noções de SolidWorks ou equivalente",
      "Disponibilidade aos sábados na oficina",
    ],
    beneficios: [
      "Certificado de atividade complementar",
      "Projeto real de engenharia do papel à pista",
      "Viagem à competição nacional",
    ],
    cursosAlvo: [1, 8, 7],
    periodoMinimo: 2,
    crMinimo: null,
    cargaHorariaSemanal: 10,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-09-27",
    responsavelNome: "Gustavo Arantes, capitão",
    responsavelContato: "baja@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-01",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 5,
  },
  {
    id: 11,
    instituicaoId: 41,
    tipo: T.EQUIPE_COMPETICAO,
    titulo: "Eletrônica embarcada e telemetria",
    descricao:
      "Desenvolvimento da aquisição de dados do carro e das placas de sensores, em C e Python, com testes em pista.",
    requisitos: [
      "Programação em C ou Python",
      "Noções de eletrônica digital",
    ],
    beneficios: [
      "Certificado de atividade complementar",
      "Experiência com sistemas embarcados de verdade",
    ],
    cursosAlvo: [2, 3, 8],
    periodoMinimo: 3,
    crMinimo: null,
    cargaHorariaSemanal: 12,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-04",
    responsavelNome: "Isabela Cruz, líder de eletrônica",
    responsavelContato: "formula@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-02",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 4,
  },
  {
    id: 12,
    instituicaoId: 42,
    tipo: T.EQUIPE_COMPETICAO,
    titulo: "Visão computacional do robô autônomo",
    descricao:
      "Programação da detecção de obstáculos para a categoria autônoma, com treinos semanais no laboratório.",
    requisitos: ["Python", "Interesse em visão computacional"],
    beneficios: ["Certificado de atividade complementar"],
    cursosAlvo: [2, 3],
    periodoMinimo: 1,
    crMinimo: null,
    cargaHorariaSemanal: 8,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    // Prazo já vencido de propósito: serve para verificar que a candidatura é
    // bloqueada e que a vaga não aparece em "inscrições abertas".
    prazoInscricao: "2026-09-10",
    responsavelNome: "Thiago Rangel, líder de software",
    responsavelContato: "robotica@puc-rio.br",
    status: S.ABERTA,
    publicadaEm: "2026-08-20",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 3,
  },

  // ===================== UFRJ =======================================
  {
    id: 13,
    instituicaoId: 20,
    tipo: T.MONITORIA,
    titulo: "Monitoria de Estruturas de Dados",
    descricao:
      "Plantão de dúvidas e correção de trabalhos das turmas de Estruturas de Dados do Instituto de Computação.",
    requisitos: ["Ter cursado Estruturas de Dados", "Domínio de C"],
    beneficios: ["Bolsa mensal", "Certificado de monitoria"],
    cursosAlvo: [2, 3],
    periodoMinimo: 3,
    crMinimo: 7.0,
    cargaHorariaSemanal: 12,
    remunerada: true,
    valorBolsa: 700,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-01",
    responsavelNome: "Prof. Henrique Lopes",
    responsavelContato: "henrique.lopes@ic.ufrj.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-04",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 3,
  },
  {
    id: 14,
    instituicaoId: 21,
    tipo: T.IC,
    titulo: "Otimização de rotas de distribuição urbana",
    descricao:
      "Modelagem e implementação de heurísticas para roteirização de entregas na região metropolitana, com dados reais de um operador logístico.",
    requisitos: [
      "Pesquisa operacional",
      "Python com bibliotecas de otimização",
    ],
    beneficios: [
      "Bolsa PIBIC por 12 meses",
      "Dados reais de operação logística",
    ],
    cursosAlvo: [1, 2],
    periodoMinimo: 5,
    crMinimo: 7.5,
    cargaHorariaSemanal: 20,
    remunerada: true,
    valorBolsa: 1100,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-12",
    responsavelNome: "Profa. Vera Nunes",
    responsavelContato: "vera.nunes@coppe.ufrj.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-05",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },
  {
    id: 15,
    instituicaoId: 33,
    tipo: T.LIGA_ACADEMICA,
    titulo: "Núcleo de projetos de inovação",
    descricao:
      "Participação em projetos de inovação com empresas do Parque Tecnológico da UFRJ, em ciclos de três meses.",
    requisitos: ["Disponibilidade para reuniões no Fundão"],
    beneficios: ["Certificado", "Contato com startups do parque tecnológico"],
    cursosAlvo: [],
    periodoMinimo: 2,
    crMinimo: null,
    cargaHorariaSemanal: 8,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-06",
    responsavelNome: "Camila Prado, coordenadora",
    responsavelContato: "nucleo@lei.ufrj.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-06",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 6,
  },
  {
    id: 16,
    instituicaoId: 43,
    tipo: T.EQUIPE_COMPETICAO,
    titulo: "Subsistema de propulsão",
    descricao:
      "Projeto, simulação e testes estáticos de motores-foguete de propelente sólido para competição internacional.",
    requisitos: ["Termodinâmica", "Disponibilidade para testes de campo"],
    beneficios: ["Certificado", "Participação em competição internacional"],
    cursosAlvo: [8, 1],
    periodoMinimo: 3,
    crMinimo: null,
    cargaHorariaSemanal: 12,
    remunerada: false,
    valorBolsa: null,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-09",
    responsavelNome: "Lucas Vidal, capitão",
    responsavelContato: "minerva@ufrj.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-07",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 5,
  },

  // ===================== UERJ =======================================
  {
    id: 17,
    instituicaoId: 22,
    tipo: T.MONITORIA,
    titulo: "Monitoria de Cálculo I",
    descricao:
      "Plantão de dúvidas para as turmas de Cálculo I do Instituto de Matemática e Estatística.",
    requisitos: ["Ter cursado Cálculo I com bom aproveitamento"],
    beneficios: ["Bolsa mensal", "Certificado de monitoria"],
    cursosAlvo: [9, 1, 7],
    periodoMinimo: 2,
    crMinimo: 7.0,
    cargaHorariaSemanal: 12,
    remunerada: true,
    valorBolsa: 550,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-07",
    responsavelNome: "Prof. Sérgio Maia",
    responsavelContato: "sergio.maia@ime.uerj.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-08",
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 4,
  },

  // ===================== Estágios (empresas) ========================
  {
    id: 18,
    instituicaoId: 50,
    tipo: T.ESTAGIO,
    titulo: "Estágio em análise de dados de operações",
    descricao:
      "Construção de relatórios de performance e apoio ao time de consultoria na leitura dos indicadores dos clientes. Rotina com SQL, Excel avançado e Power BI.",
    requisitos: [
      "Excel avançado",
      "SQL básico",
      "Disponibilidade de 30h semanais",
    ],
    beneficios: [
      "Bolsa de R$ 2.200 e vale-transporte",
      "Plano de carreira com efetivação",
      "Mentoria com consultor sênior",
    ],
    cursosAlvo: [1, 4, 2],
    periodoMinimo: 4,
    crMinimo: 7.0,
    cargaHorariaSemanal: 30,
    remunerada: true,
    valorBolsa: 2200,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-09-29",
    responsavelNome: "Camila Duarte, gente e gestão",
    responsavelContato: "vagas@visagio.com",
    status: S.ABERTA,
    publicadaEm: "2026-09-01",
    // Publicada para PUC-Rio e UFRJ apenas — aluno da UERJ não enxerga.
    universidadesAlvo: [1, 2],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 3,
  },
  {
    id: 19,
    instituicaoId: 51,
    tipo: T.ESTAGIO,
    titulo: "Estágio em produto e dados",
    descricao:
      "Apoio na construção dos painéis de acompanhamento e nas rotinas de qualidade da base de investimentos.",
    requisitos: ["Excel avançado", "Interesse em mercado financeiro"],
    beneficios: [
      "Bolsa de R$ 1.800 mais benefícios",
      "Contato direto com as áreas de análise",
    ],
    cursosAlvo: [4, 1, 5],
    periodoMinimo: 3,
    crMinimo: null,
    cargaHorariaSemanal: 20,
    remunerada: true,
    valorBolsa: 1800,
    modalidade: M.PRESENCIAL,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-06",
    responsavelNome: "Rodrigo Paes, coordenador de BI",
    responsavelContato: "estagio@opportunity.com.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-03",
    // Vazio = todas as universidades.
    universidadesAlvo: [],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },
  {
    id: 20,
    instituicaoId: 52,
    tipo: T.ESTAGIO,
    titulo: "Estágio em engenharia de processos",
    descricao:
      "Levantamento de tempos de linha e apoio nos projetos de melhoria contínua da planta de Duque de Caxias.",
    requisitos: [
      "Conhecimento de Lean ou Seis Sigma",
      "Disponibilidade para atuar presencialmente em Caxias",
    ],
    beneficios: ["Bolsa de R$ 2.000 e refeição no local", "Projeto próprio de melhoria"],
    cursosAlvo: [1, 8],
    periodoMinimo: 5,
    crMinimo: null,
    cargaHorariaSemanal: 30,
    remunerada: true,
    valorBolsa: 2000,
    modalidade: M.PRESENCIAL,
    cidade: "Duque de Caxias, RJ",
    prazoInscricao: "2026-10-12",
    responsavelNome: "Luiza Menezes, engenharia",
    responsavelContato: "rh@nortecindustria.com.br",
    status: S.ABERTA,
    publicadaEm: "2026-09-05",
    universidadesAlvo: [1, 2, 3],
    formaCandidatura: FORMA_CANDIDATURA.EXTERNA,
    linkExterno: "https://nortecindustria.com.br/carreiras/estagio-processos",
    vagas: 1,
  },
  {
    id: 21,
    instituicaoId: 50,
    tipo: T.ESTAGIO,
    titulo: "Estágio em tecnologia e automação",
    descricao:
      "Desenvolvimento de automações internas e integrações entre sistemas de clientes, em Python.",
    requisitos: ["Python", "Noções de API REST"],
    beneficios: ["Bolsa de R$ 2.400", "Time de tecnologia com code review semanal"],
    cursosAlvo: [2, 3],
    periodoMinimo: 4,
    crMinimo: 7.0,
    cargaHorariaSemanal: 30,
    remunerada: true,
    valorBolsa: 2400,
    modalidade: M.HIBRIDO,
    cidade: "Rio de Janeiro, RJ",
    prazoInscricao: "2026-10-20",
    responsavelNome: "Camila Duarte, gente e gestão",
    responsavelContato: "vagas@visagio.com",
    status: S.ABERTA,
    publicadaEm: "2026-09-08",
    universidadesAlvo: [1, 2],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 2,
  },
  {
    id: 22,
    instituicaoId: 52,
    tipo: T.ESTAGIO,
    titulo: "Estágio em qualidade",
    descricao:
      "Apoio na rotina de inspeção e no tratamento de não conformidades da planta.",
    requisitos: ["Interesse em qualidade e processos"],
    beneficios: ["Bolsa de R$ 1.900", "Certificação interna em qualidade"],
    cursosAlvo: [1],
    periodoMinimo: 3,
    crMinimo: null,
    cargaHorariaSemanal: 25,
    remunerada: true,
    valorBolsa: 1900,
    modalidade: M.PRESENCIAL,
    cidade: "Duque de Caxias, RJ",
    prazoInscricao: "2026-10-18",
    responsavelNome: "Luiza Menezes, engenharia",
    responsavelContato: "rh@nortecindustria.com.br",
    // Rascunho: não aparece para aluno nenhum, só no painel de quem publicou.
    status: S.RASCUNHO,
    publicadaEm: null,
    universidadesAlvo: [1, 2, 3],
    formaCandidatura: FORMA_CANDIDATURA.PLATAFORMA,
    linkExterno: "",
    vagas: 1,
  },
];

export const acharOportunidade = (id) =>
  oportunidades.find((o) => o.id === Number(id)) || null;
